# Site settings
title: Jesse's blog
email: jesse@jessewhite.ca
description: > # this means to ignore newlines until "baseurl:"
  My personal blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.jessewhite.ca"
github_username:  j-white

# Build settings
markdown: kramdown
highlighter: pygments
